# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'Jelly', '~> 2.2.2'
  pod 'LTMorphingLabel'
  use_frameworks!

  # Pods for CocoaPods

end
